// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFolder = "folder"

// Folder mapped from table <folder>
type Folder struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TargetID  int64     `gorm:"column:target_id" json:"target_id"` // 目标id
	Request   string    `gorm:"column:request;not null" json:"request"`
	Script    string    `gorm:"column:script;not null" json:"script"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Folder's table name
func (*Folder) TableName() string {
	return TableNameFolder
}
