// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOperation = "operation"

// Operation mapped from table <operation>
type Operation struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TeamID    int64          `gorm:"column:team_id;not null" json:"team_id"`
	UserID    int64          `gorm:"column:user_id;not null" json:"user_id"`
	Category  int32          `gorm:"column:category;not null" json:"category"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Operation's table name
func (*Operation) TableName() string {
	return TableNameOperation
}
