// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePlan = "plan"

// Plan mapped from table <plan>
type Plan struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TeamID    int64          `gorm:"column:team_id;not null" json:"team_id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Status    int32          `gorm:"column:status;not null" json:"status"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Plan's table name
func (*Plan) TableName() string {
	return TableNamePlan
}
