// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameReport = "report"

// Report mapped from table <report>
type Report struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Mode      int32          `gorm:"column:mode;not null" json:"mode"`
	Status    int32          `gorm:"column:status;not null" json:"status"`
	RanAt     time.Time      `gorm:"column:ran_at;not null;default:CURRENT_TIMESTAMP" json:"ran_at"`
	RunUserID int64          `gorm:"column:run_user_id;not null" json:"run_user_id"`
	TeamID    int64          `gorm:"column:team_id;not null" json:"team_id"`
	TaskType  int32          `gorm:"column:task_type;not null" json:"task_type"`
	SceneType int32          `gorm:"column:scene_type;not null" json:"scene_type"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Report's table name
func (*Report) TableName() string {
	return TableNameReport
}
