// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserTeam = "user_team"

// UserTeam mapped from table <user_team>
type UserTeam struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64          `gorm:"column:user_id;not null" json:"user_id"`
	TeamID    int64          `gorm:"column:team_id;not null" json:"team_id"`
	RoleID    int64          `gorm:"column:role_id;not null" json:"role_id"`
	Sort      int32          `gorm:"column:sort;not null" json:"sort"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserTeam's table name
func (*UserTeam) TableName() string {
	return TableNameUserTeam
}
