// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVariableImport = "variable_import"

// VariableImport mapped from table <variable_import>
type VariableImport struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TeamID     int64     `gorm:"column:team_id" json:"team_id"`
	SceneID    int64     `gorm:"column:scene_id" json:"scene_id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	URL        string    `gorm:"column:url;not null" json:"url"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	UploaderID int64     `gorm:"column:uploader_id;not null" json:"uploader_id"`
}

// TableName VariableImport's table name
func (*VariableImport) TableName() string {
	return TableNameVariableImport
}
