// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameVariable = "variable"

// Variable mapped from table <variable>
type Variable struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TeamID      int64          `gorm:"column:team_id;not null" json:"team_id"`
	Var         string         `gorm:"column:var;not null" json:"var"`
	Val         string         `gorm:"column:val;not null" json:"val"`
	Description string         `gorm:"column:description" json:"description"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Variable's table name
func (*Variable) TableName() string {
	return TableNameVariable
}
