// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePlan = "plan"

// Plan mapped from table <plan>
type Plan struct {
	ID                 int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TeamID             int64          `gorm:"column:team_id;not null" json:"team_id"`
	Rank               int64          `gorm:"column:rank;not null" json:"rank"`
	Name               string         `gorm:"column:name;not null" json:"name"`
	TaskType           int32          `gorm:"column:task_type" json:"task_type"`
	Mode               int32          `gorm:"column:mode" json:"mode"`
	Status             int32          `gorm:"column:status;not null" json:"status"`
	CreateUserIdentify string         `gorm:"column:create_user_identify;not null" json:"create_user_identify"`
	RunUserIdentify    string         `gorm:"column:run_user_identify;not null" json:"run_user_identify"`
	CreateUserID       int64          `gorm:"column:create_user_id;not null" json:"create_user_id"`
	RunUserID          int64          `gorm:"column:run_user_id;not null" json:"run_user_id"`
	Remark             string         `gorm:"column:remark" json:"remark"`
	CronExpr           string         `gorm:"column:cron_expr" json:"cron_expr"`
	CreatedAt          time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Plan's table name
func (*Plan) TableName() string {
	return TableNamePlan
}
