base:
  is_debug:
  domain:
  max_concurrency:

http:
  port: 20123

mysql:
  username:
  passport:
  host:
  port:
  dbname:
  charset:

mongodb:
  dsn:
  database:
  pool_size:

jwt:
  issuer:
  secret:


clients:
  runner:
    run_api:
    run_scene:
    stop_scene:
    run_plan:
    stop_plan:

proof:
  info_log:
  err_log:

redis:
  address:
  password:
  db: 0

redis_report:
  address:
  password:
  db: 0

smtp:
  host:
  port:
  email:
  password:
  #新邮箱-待启用
  #email: ""
  #password: ""
