base:
  is_debug: false
  domain: "https://kp-test-fe.apipost.cn/"

http:
  port: 20123

mysql:
  username: "test_read_only"
  passport: "db#01^st$Post"
  host: "rm-2zem14s80lyu5c4z7.mysql.rds.aliyuncs.com"
  port: 3306
  dbname: "kunpeng"
  charset: "utf8mb4"

mongodb:
  dsn: "mongodb://kunpeng:kYjJpU8BYvb4EJ9x@172.17.18.255:27017/kunpeng"
  database: "kunpeng"
  pool_size: 20

jwt:
  issuer: "kp"
  secret: "kp#test"

prometheus:
  host: "172.17.101.189"
  port: 9090

es:
  host: "http://es-cn-7pp2x5zd10001vn8v.elasticsearch.aliyuncs.com:9200"
  username: "elastic"
  password: "dnRqw5rRicYjbkkE"
  index: "report"
  size: 10000000

clients:
  runner:
    run_api: "https://kprunner.apipost.cn/runner/run_api"
    run_scene: "https://kprunner.apipost.cn/runner/run_scene"
    stop_scene: "https://kprunner.apipost.cn/runner/stop_scene"
    run_plan: "https://kprunner.apipost.cn/runner/run_plan"
    stop_plan: "https://kprunner.apipost.cn/runner/stop"

proof:
  info_log: "/data/logs/kp-management/info.log"
  err_log: "/data/logs/kp-management/err.log"

redis:
  address: "172.17.101.191:6398"
  password: "apipost"
  db: 0

smtp:
  host: "smtpdm.aliyun.com"
  port: 465
  email: "findpwd@no-reply.apipost.cn"
  password: "BIyela4341"
